In [1]:
import numpy as np

In [2]:
#numpy array

a= np.array([34,67,8,5,33,90,23])
print(a)

[34 67  8  5 33 90 23]


In [3]:
#type

type(a)

numpy.ndarray

In [4]:
#length

len(a)

7

In [5]:
print(a[2])

8


In [6]:
b=np.array([[77, 38, 9], [10, 11, 12]])

In [7]:
print(b)

[[77 38  9]
 [10 11 12]]


In [8]:
len(b)

2

In [9]:
b.shape

(2, 3)

In [10]:
c = np.arange(0, 50, 3) # start at 0 count up by 3, stop before 50

In [11]:
print(c)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [12]:
d = np.arange(0, 52, 3) # start at 0 count up by 3, stop before 52

In [13]:
print(d)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51]


In [14]:
e= np.arange(25,50)

In [15]:
len(e)

25

In [16]:
print(e)

[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [17]:
f= e.reshape(5, 5)

In [18]:
print(f)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [19]:
len(f)

5

In [20]:
f.shape

(5, 5)

In [21]:
a1 = np.linspace(0, 10, 20) # return 19 evenly spaced values from 0 to 4

In [22]:
print(a1)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [23]:
len(a1)

20

In [24]:
a2=a1.reshape(5,4)  #reshape

In [25]:
print(a2)

[[ 0.          0.52631579  1.05263158  1.57894737]
 [ 2.10526316  2.63157895  3.15789474  3.68421053]
 [ 4.21052632  4.73684211  5.26315789  5.78947368]
 [ 6.31578947  6.84210526  7.36842105  7.89473684]
 [ 8.42105263  8.94736842  9.47368421 10.        ]]


In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones([6,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [28]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [31]:
y=np.array([6,78,3,56,89])

np.diag(y)

array([[ 6,  0,  0,  0,  0],
       [ 0, 78,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0, 56,  0],
       [ 0,  0,  0,  0, 89]])

In [32]:
np.array([1, 2, 3,7] * 3)

array([1, 2, 3, 7, 1, 2, 3, 7, 1, 2, 3, 7])

In [33]:
np.repeat([1, 4, 2, 3], 5)

array([1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [34]:
p = np.ones([2, 3], int)
print(p)

[[1 1 1]
 [1 1 1]]


In [35]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [36]:
np.vstack([2*p, 7*p])


array([[2, 2, 2],
       [2, 2, 2],
       [7, 7, 7],
       [7, 7, 7]])

In [37]:
np.vstack([3*p, 2*p, 6.5*p,4.6*p])


array([[3. , 3. , 3. ],
       [3. , 3. , 3. ],
       [2. , 2. , 2. ],
       [2. , 2. , 2. ],
       [6.5, 6.5, 6.5],
       [6.5, 6.5, 6.5],
       [4.6, 4.6, 4.6],
       [4.6, 4.6, 4.6]])

In [38]:
np.hstack([2*p,5.5*p,9*p])

array([[2. , 2. , 2. , 5.5, 5.5, 5.5, 9. , 9. , 9. ],
       [2. , 2. , 2. , 5.5, 5.5, 5.5, 9. , 9. , 9. ]])