In [1]:
import numpy as np

In [2]:
a=np.array([4,6,8])
b=np.array([8,9,7])

c=a+b

print(c)

[12 15 15]


In [3]:
a=np.array([4,6,8])
b=np.array([8,9,7])

c=a*b

print(c)

[32 54 56]


In [4]:
a=np.array([4,6,8])
b=np.array([8,9,7])

c=a/b

print(c)

[0.5        0.66666667 1.14285714]


In [7]:
c=np.array([6,7,5,8])
d=np.array([4,3,7,8])

ans=c.dot(d)  #dot product

print(ans)

144


In [14]:
z=np.array([[5,7,5,4,5],[6,2,3,4,6]])

print(z)

[[5 7 5 4 5]
 [6 2 3 4 6]]


In [16]:
print(z.T)

[[5 6]
 [7 2]
 [5 3]
 [4 4]
 [5 6]]


In [17]:
h=np.arange(4,90,5)

In [18]:
print(h)

[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89]


In [19]:
h.sum()

837

In [20]:
h.max()

89

In [21]:
h.min()

4

In [22]:
h.mean()

46.5

In [23]:
h.std()

25.940637360455632

In [24]:
h.argmax()

17

In [25]:
h.argmin()

0

In [26]:
#Iterating Over Arrays


In [27]:
test = np.random.randint(0,10,(4,3))
print(test)

[[5 0 2]
 [3 6 0]
 [5 7 7]
 [0 5 9]]


In [28]:
test2 = np.random.randint(90,120,(8,3))
test2

array([[106, 103, 104],
       [ 96,  93, 106],
       [110, 108, 115],
       [117, 106, 114],
       [ 91, 102, 103],
       [ 98, 104,  92],
       [112,  99, 105],
       [115, 111, 118]])

In [30]:
for row in test2:
    print(row)

[106 103 104]
[ 96  93 106]
[110 108 115]
[117 106 114]
[ 91 102 103]
[ 98 104  92]
[112  99 105]
[115 111 118]


In [31]:
for i in range(len(test2)):
    print(test2[i])

[106 103 104]
[ 96  93 106]
[110 108 115]
[117 106 114]
[ 91 102 103]
[ 98 104  92]
[112  99 105]
[115 111 118]


In [32]:

test3 = test2**2
test3

array([[11236, 10609, 10816],
       [ 9216,  8649, 11236],
       [12100, 11664, 13225],
       [13689, 11236, 12996],
       [ 8281, 10404, 10609],
       [ 9604, 10816,  8464],
       [12544,  9801, 11025],
       [13225, 12321, 13924]], dtype=int32)

In [33]:
for i, j in zip(test2, test3):
    print(i,'+',j,'=',i+j)

[106 103 104] + [11236 10609 10816] = [11342 10712 10920]
[ 96  93 106] + [ 9216  8649 11236] = [ 9312  8742 11342]
[110 108 115] + [12100 11664 13225] = [12210 11772 13340]
[117 106 114] + [13689 11236 12996] = [13806 11342 13110]
[ 91 102 103] + [ 8281 10404 10609] = [ 8372 10506 10712]
[ 98 104  92] + [ 9604 10816  8464] = [ 9702 10920  8556]
[112  99 105] + [12544  9801 11025] = [12656  9900 11130]
[115 111 118] + [13225 12321 13924] = [13340 12432 14042]
